### ISSUE TITLE
display multiple properties

### ISSUE THREAD

**Issue by sukumarkonduru** [czeckd/custom-dual-listbox#3]
David,  I need  to display each item as 3 lines (name,company, position).  Right now "display"  input property allows to select only one property from the object to be displayed in the list box.

How I can accomplish what I need. I guess we need to point display for 3 properties and show those in 3 paragraph items.  I am using custom-dual-listbox. Appreciate any suggestions.

**Comment by czeckd** [comment]
You'll need to override the function: 
```typescript
private makeName(item:any) : string [
  ...
}
```
But, I see I made it private, so you'll get ERRORs when you do so. I'll get a new release of the angular-dual-listbox out that will fix this issue so the function can be overridden.

**Comment by czeckd** [comment]
Another option is to not call that function and override 
```typescript
buildAvailable(source:Array<any>) : boolean {
  ...
    this.available.list.push( { _id: this.makeId(r.item), _name: this.makeName(r.item) });
  ...
}
```
and  instead of calling `makeName`, call your own function to make a name. Then in your template style the label however you want.

**Comment by czeckd** [comment]
In your template, you'll want to change the label to show innerHTML instead of the text string. So instead of this:
```html
<label>{{item._name}}</label>
```
Do this:
```html
<label [innerHTML]="item._name"></label>
```

Then in your replacement `makeName` function, you could format your separate fields with `<p>` marks or add css mark-up as needed to format the display to meet your requirements.

**Comment by sukumarkonduru** [comment]
Thanks David. Yeah I tried to override makename before  and realized being private. I will get new code and do modifications you mentioned. Thanks for taking time to provide suggestions.

**Comment by sukumarkonduru** [comment]
I just  overridden makeName() method and updated label to use innerhtml property and it is working good. I used following snippet in getName()
//	str = str + item[this.display[i]];
					str= str + "<p>"+ item[this.display[i]] + "</p>";
Thanks for the excellent work providing updated code with tips.  I feel good to know  method how works and innhehtml property. I will update css later.

**Comment by kfinch217** [comment]
Can I see the repo for this.  I'm trying to do something similar and want replace the default separator with a space as well.  I'm new to angular so this is kind of confusing for me

**Comment by Pawindtaore** [comment]
hello friends. I have the same problem. I tried like you suggested @czeckd but I don't really understand your solution.  I'll really appreciate some help.
