### ISSUE TITLE
After  click on add update  back end through  httpclient

### ISSUE THREAD

**Issue by sukumarkonduru** [czeckd/custom-dual-listbox#4]
After user clicks on  add button to right or left, I need to update  my own objects from arrays of source/destination and also update  in the back-end using httpclient. I am wondering  what would be easy change  that allows to complete what is needed.

Wondering if I need to place  after moveItem.
(click)="moveItem(available, confirmed)"
 Appreciate for any suggestions.

**Comment by czeckd** [comment]
You could use (destinationChange) to trigger whatever you need on the backend. See this [comment](https://github.com/czeckd/angular-dual-listbox/issues/63#issuecomment-358075326).

**Comment by sukumarkonduru** [comment]
Thanks for the tip. I am able to use this event.  Here is the  call back method updateKeyContact for this event. 
//call bck method
updateKeyContact(e:any) {
    for(let i=0; i<this.target.length; i++){
      this.target[i].keyContact=true;
    }
    this.source.forEach((contact) => contact.keyContact=false);
console.log("source",this.source);
console.log("target",this.target);
    
	}
}
I noticed following when I print arrays.
1. source is being same length.  Data is not being moved to the destination. I even tried this [(source)]="source" with two way binding.
2.  I update keycontact  property as true first in destination then in source. I find  the value is false when I print target array. I guess source/target could be sharing same data.

Appreciate any suggestions.
--------------------------------------------------------------------------------------------

**Comment by czeckd** [comment]
Per design, the source does not change through the DualListboxComponent. Items do not move out of the source into the destination and vice-versa. Items are added to and subtracted from the destination. If you need to see changes in the source, then you will need to do a difference between the source and the destination arrays.

Again per design, changes to the destination array do not impact the source array. If you update a property of an element in the destination, you will also need to do the same to the source.

**Comment by sukumarkonduru** [comment]
Thanks David for the clarification and link. I will update for this design.  I am curious on one thing. If you look at snippet,  I am making keyContact property to be true for all items in the destination array and then to be false on source array. However, I see all values are false.  Are items from the destination are still references to those in source array? I see number of items is  source array same as you mentioned.

**Comment by czeckd** [comment]
Think of the dual-listbox as more like an html <[select multiple](https://www.w3schools.com/tags/att_select_multiple.asp)>. From what you're doing, the dual-listbox may not be the best component for the job. Have you thought about just having a <ul> list with your items and a checkbox for the 'keyContact' field?
