### ISSUE TITLE
How To Create Custom List Elements

### ISSUE THREAD

**Issue by np161** [czeckd/custom-dual-listbox#7]
How would go about adding extra HTML elements to the items. I would like to be able to display the name on the left but also be able to display associated icons or progress bars on the right. Is this possible with your component?

**Comment by czeckd** [comment]
I would probably change the template for the `<li>` that make up each list element to set the `[innerHTML]` and then use a bound function from the parent component passed as the `[display]="functionName"` to the component used in the template.

The bound function would return HTML to put in the `<li [innerHTML]="name">` for  the dual list. It would  probably also need to use DomSanitizer to make the html passed from the bound function to the name variable to be trusted HTML.

**Comment by np161** [comment]
Thanks for the reply.
I am kinda new to Angular so may not fully understand what you are saying. would it be that the function I set display to should return '<li [innerHtml] = "image html tag">'

Could you point me to some examples because I'm not sure I fully understand

**Comment by czeckd** [comment]
I created an example on [Stackblitz here](https://stackblitz.com/edit/angular-gpnlbl).

Key points are:
-  A `[SafeHtmlPipe]` [pipe](https://stackblitz.com/edit/angular-gpnlbl?file=app%2Fcustom-listbox%2Fsafe-html.pipe.ts)` to allow for the programatic styling.
- A custom listbox with a customized [template](https://stackblitz.com/edit/angular-gpnlbl?file=app%2Fcustom-listbox%2Fcustom-listbox.component.html) that uses the pipe and uses `[innerHTML]`:
```html
<label [innerHTML]="item._name|safe"></label>
```
- A [display function](https://stackblitz.com/edit/angular-gpnlbl?file=app%2Fapp.component.ts) to set the icon:
```ts
  iconDisplay(e:any) : string {
    return e._name + ' <i class="fa fa-' + e._icon + '"></i>';
  }
```
And then using the function for display with the custom listbox in the [template](https://stackblitz.com/edit/angular-gpnlbl?file=app%2Fapp.component.html):
```html
<app-custom-listbox [source]="source" [(destination)]="confirmed"
  height="200px" [display]="iconDisplay"></app-custom-listbox>
```

Lastly, here's the Angular.io page on security about [cross-site scripting](https://angular.io/guide/security#xss), which will help explain why the html needs to be trusted. 

There are other approaches to styling the list, of course, but this one was a quick way of doing it. Other approaches would be a rewrite to put the icon code inside the custom dual listbox itself.

Good luck!

**Comment by np161** [comment]
Thank you for that it was very helpful. I do have one last question is it possible to pass any parameters/values into the iconDisplay function. I am trying to do an if statement inside of it but the value I am checking is undefined even though it works everywhere else.

**Comment by czeckd** [comment]
In the place where you have your display function, bind it to `this`. So in the example in app.component.ts, it'd be something like this:
```typescript
export class AppComponent {
  iconDisplayBound = this.iconDisplay.bind(this);

  // and so on...
```
Then in the html, used the variable bound:
```html
<app-custom-listbox [source]="source" [(destination)]="confirmed"
  height="200px" [display]="iconDisplayBound"></app-custom-listbox>
```

**Comment by np161** [comment]
Thanks for all the help everything is working fine now
