### ISSUE TITLE
How to add filter input field?

### ISSUE THREAD

**Issue by gsanj** [czeckd/custom-dual-listbox#8]
I added **filter = true** in component also added the following tag
<app-custom-listbox [source]="source" [key]="key" [display]="display" [(destination)]="target" height="200px" **[filter]="filter"** ></app-custom-listbox> but filter is not showing in html page.
Please suggest me what mistake I am doing?

**Comment by czeckd** [comment]
Does your custom template still have a filter to show for each list? Each list will need something like this:
```html
<form *ngIf="filter" class="filter">
  <input class="form-control" name="filterSource" [(ngModel)]="available.picker"
    (ngModelChange)="onFilter(available)">
</form>
```

**Comment by gsanj** [comment]
@czeckd  Thanks for your quick response. It is working fine.

**Comment by sminodonte** [comment]
I'm sorry but I don't understand where I have to put this kind of code:

`<form *ngIf="filter" class="filter">
  <input class="form-control" name="filterSource" [(ngModel)]="available.picker"
    (ngModelChange)="onFilter(available)">
</form>`

**Comment by Reemzaki** [comment]
Hello I am trying to add  the filter feature , the input field appears but it's not working I have done all the steps I added in the custome tlist Template : 
<form *ngIf="filter" class="filter">
  <input class="form-control" name="filterSource" [(ngModel)]="available.picker"
    (ngModelChange)="onFilter(available)">
</form>

also added in my html :  [filter]="filter" 
and in my ts : filter = true  
but its not working
