### ISSUE TITLE
How can we show same objects in both list?

### ISSUE THREAD

**Issue by gsanj** [czeckd/custom-dual-listbox#9]
As per my requirement we have two list, List A have some objects and List B have some objects. **List B have some objects those are already exist in List A** (Means same objects in both list), In this scenario current implementation is showing common objects in List B. But as per my requirement it should show in both list. How can we show same objects in both list?

**Comment by czeckd** [comment]
Is your requirement for items in List A always be displayed even if they are in List B? If that's the case you could do something like this in your customization:
```typescript
    constructor(differs:IterableDiffers) {
        super(differs);

        // Override private function in super class.
        this['makeUnavailable'] = function(source:BasicList, item:any) {
            if (source.name !== DualListComponent.AVAILABLE_LIST_NAME) {
                const idx = source.list.indexOf(item);
                if (idx !== -1) {
                    source.list.splice(idx, 1);
                }
            }
        }
    }
```

**Comment by gsanj** [comment]
Your scenario is also fine but It is showing duplicate objects. I found some other solution with different IDS that working fine. Thanks for your response. Please close this issue.
